### PR TITLE
Adding support to scale in the scaffold

### PR DESCRIPTION
**Pull request by deividfortuna**
This PR will adding the possibility of scale the scaffold allow user to create an effect of having the scaffold over the menu.

image
https://dribbble.com/shots/6351511-Menu-and-Dashboard/attachments

### CODE REVIEW

**Comment by Dn-a** [comment]
@deividfortuna 
wow!
It looks fantastic. give me time to try it

**Comment by Dn-a** [comment]
@deividfortuna I tried it but there are a number of things to consider. the width of the child is not proportional to the scale. the problem is most evident when setting the position at the end. with animations (linear, quadratic) it is not applicable because the background remains black.

**Comment by deividfortuna** [comment]
@Dn-a thanks for the feedback, let me try take a look on that. I'm a newbie in flutter, so I may not be able to fix 😞

**Comment by Dn-a** [comment]
@deividfortuna if you can't, I can implement it in the next releases

**Comment by furkankurt** [comment]
It will be awesome!! I'm waiting!

**Pull request closed without merging**
