### PR TITLE
support null-safety

### PR DESCRIPTION
**Pull request by chavesgu**

### CODE REVIEW

**Comment by seekcx** [comment]
LGTM

**Comment by deakjahn** [comment]
@chavesgu Please, move the version number to 1.0.0.

**Comment by AliHoseinpoor** [comment]
please support null safety

**Comment by Dn-a** [comment]
Hi @chavesgu, I cannot accept your pull request because I have made some improvements. Now you can use version 1.0.0 which supports null safety.

**Comment by chavesgu** [comment]
You don't accept mine,You released 1.0 yourself,but yours has bug.

**Pull request closed without merging**
